# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20161117_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='Trailer',
            field=models.CharField(default='', max_length=2500),
        ),
    ]
