# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movieinfo_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='Price',
            field=models.CharField(default='', max_length=25),
        ),
    ]
